{"error":"Error: Este es un error de prueba\n    at <anonymous> (/Users/monard/Documents/ControlFinanciero_app/server/test-logs.ts:7:30)\n    at ModuleJob.run (node:internal/modules/esm/module_job:329:25)\n    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)\n    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)","level":"error","message":"Error de prueba","timestamp":"2025-08-31T02:30:35.305Z"}
{"level":"error","message":"Error de autenticaci√≥n","timestamp":"2025-08-31T02:30:35.306Z"}
